### ISSUE TITLE
What's the difference http://www.skbuff.net/iputils

### ISSUE THREAD

**Issue by peterwillcn** [iputils/iputils#165]
What's the difference ？
https://github.com/openwrt/openwrt/pull/1804
http://www.skbuff.net/iputils

**Comment by okias** [comment]
Hello Peter,

difference is original maintainer did not accepting patches, so I offered him long time ago this repository including all infrastructure (travis-ci etc.). Sadly, my message got no responce from his side and since then this repository of iputils is upstream for most distributions.

Of course, if previous maintainer is willing to work on this project and accept patches, I have no problem grant him permissions to this repository.

These days, most of development and maintaining is done by Sami Kerola.

**Comment by pevik** [comment]
@okias @kerolasa I guess we can close this.
