### ISSUE TITLE
Ping reports DUP responses when pinging multicast destinations

### ISSUE THREAD

**Issue by nmeyerhans** [iputils/iputils#195]
Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=498429

> PING ff02::1(ff02::1) from fe80::211:2fff:fe6b:c869 lan: 56 data bytes
> 64 bytes from fe80::211:2fff:fe6b:c869: icmp_seq=1 ttl=64 time=0.036 ms
> 64 bytes from fe80::200:cbff:fe02:2e7b: icmp_seq=1 ttl=64 time=0.323 ms (DUP!)
> 
> The manpage suggests that
> 
>    Duplicate packets should never  occur,  and seem to be caused by
>    inappropriate link-level retransmissions.
> 
> but in this case, the behaviour is expected and proper, since
> a multicast address is being pinged. ping6 should probably hide the
> DUP! warning in that case.

**Comment by kerolasa** [comment]
I just added a commit to my repository (see above). I think that will do what is needed, getting the change tested would be great.

**Comment by kerolasa** [comment]
First idea did not work, so I pushed this change slightly differently, see commit 918b876a5eb1e8bffe1a56c5697064c6dc80a141 that should address the issue. Notice that the updated change is based on testing results after I got my ISP[1] to turn on IPv6 so that I can see how the code behaves.

[1] thanks Zen internet.
