### ISSUE TITLE
Disable setcap and setuid for arping (prevent ARP Poisoning)

### ISSUE THREAD

**Issue by pevik** [iputils/iputils#203]
Disable setcap and setuid for arping as it can be used for ARP Poisoning
https://en.wikipedia.org/wiki/ARP_spoofing

**Comment by pevik** [comment]
@nmeyerhans setuid is also enabled for Debian
https://salsa.debian.org/debian/iputils/blob/master/debian/iputils-arping.postinst

**Comment by nmeyerhans** [comment]
Yes, we do install arping in Debian such that unprivileged users can run it. This has been the case since the beginning of time. Since arping isn't installed by default, and Debian provides an easy mechanism by which an admin can change the permissions of a file like the arping binary in such a way that the change is preserved across package upgrades, this hasn't been considered a major concern. It's worth reconsidering that decision, though. Thanks for raising the issue.

**Comment by pevik** [comment]
This has been fixed by 054670a.
