### ISSUE TITLE
Return value of ping

### ISSUE THREAD

**Issue by tailot** [iputils/iputils#222]
Hi, Ping (with param -c) currently seems to return an error (status 1) if the host does not respond. I attach an example screen.

Regards
Vincenzo Tilotta
![a (2)](https://user-images.githubusercontent.com/40148896/67805863-1706c680-fa92-11e9-8e9e-41b8b64c3b79.png)

**Comment by kerolasa** [comment]
Do you have opinion what should it return and why.

**Comment by tailot** [comment]
@kerolasa In POSIX, programs that successfully end must return the value 0, otherwise return the value 1 to 127. In the last case, ping doesn’t seem to have any big problems.

**Comment by nmeyerhans** [comment]
@tailot Since you've invoked POSIX... POSIX doesn't specify the existence of ping at all, let alone define its error states. Thus, what constitutes an error is up to the authors. Given that ping is a tool for testing the reachability of a remote host, it is perfectly reasonably to define the unreachability of a host as an error condition. IMO, if anything about ping should be changed, it's that the manual doesn't describe the possible exit codes.

I think we'd hear loud howls of protest from all corners of the internet if we changed this behavior of ping today. Programmatically testing the reachability of a host would require either custom tooling or parsing the output of ping, either of which would make people unhappy.

It may also be worth referring to [FreeBSD's ping(8) man page](https://www.freebsd.org/cgi/man.cgi?query=ping&apropos=0&sektion=8&manpath=FreeBSD+12.0-RELEASE+and+Ports&arch=default&format=html), which does contain an "EXIT STATUS" section and does describe a nonzero exit code in case a reachability test fails.

**Comment by tailot** [comment]
I agree with you. My man is different from yours is not present the section "EXIT STATUS". I request the package manager to update.
