### ISSUE TITLE
Please use more common versioning scheme

### ISSUE THREAD

**Issue by AMDmi3** [iputils/iputils#269]
iputils historically uses versioning scheme `sYYYYMMDD`. This is pretty uncommon, not compatible with some packaging systems which do not allow random characters or cannot compare them properly, and have to mangle versions to `YYYYMMDD`:

https://repology.org/project/iputils/information

This is confusing for packagers and users, hinders automatic detection and reporting of latest version to keep packages up to date and which is more iportant, breaks comparison of package versions to versions attached to CVEs to report vulnerable packages. For instance, existing CVEs for iputils:

https://repology.org/project/iputils/cves

use third incorrect versioning scheme `YYYY-MM-DD`. It can be fixed to official `sYYYYMMDD`, but it cannot be correctly compared to `YYYYMMDD` used in packages, so I suggest to switch to more portable numeric-only scheme right away.

**Comment by kerolasa** [comment]
I agree the version string is strange. It would be much better to follow https://semver.org/ but if we change the version string will downstream packaging software (deb, rpm, pacman, and so on) get confused what is the latest version? 

It would be catastrophic to make version string such that next upgrade requires removal of all old packages from package repositories. Assuming smooth upgrades cannot be guaranteed then renaming the project to fix the version string might be the only way to fix this. But that is another can of worms. Maybe downstream packaging folks could advice what would be least worse option. cc: @nmeyerhans / @pevik

Relates to https://github.com/iputils/iputils/issues/234

**Comment by AMDmi3** [comment]
> better to follow https://semver.org/

This would be great, but yes - it may cause inconveniences (not catastrophic ones though) for some parties. In fact, most packaging systems should have no problems with this as they use _epochs_ which are increased when normal package version needs to go down due to upstream schema change or update revert, so (epoch,version) always remains monotonic. In Repology, a rule would have to be added which works similarly. If new CVE affecting iputils appears, it would have to list two version ranges, etc.

As said, these are more of inconveniences than real problems, so I'd say that if you feel like your project would benefit from semver (e.g. there's need to convey whether an update has breaking changes, just new features or is a mere bugfix release), you should go semver. Otherwise, removing `s` prefix would be just enough and will definitely cause no breakage for anyone.

**Comment by nmeyerhans** [comment]
I agree that the current scheme is a bit weird. I'm ambivalent as to whether or not it should be changed, and to whether or not semver makes sense. IMO semver is more useful for libraries or tools with explicitly machine-parseable interfaces, which doesn't qualify here, although I recognize that parsing ping's output is very common.

I don't agree with the assertion that the current scheme is particularly confusing to users, or that it's hard for package management systems to cope with. Date-based releases have been in use since forever, and the leading `s` character doesn't change anything about how the releases sort.

If the versioning scheme were to change, all common package management systems have mechanisms to cope. Usually this is done by incrementing a so-called epoch, an example of which is described in [debian-policy](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version), along with some [commentary on their use](https://www.debian.org/doc/debian-policy/ch-controlfields.html#epochs-should-be-used-sparingly).

**Comment by pevik** [comment]
Although I don't like `s` in the version, I'd prefer not introducing the change. Although first versions from Alexey Kuznetsov used different scheme (see http://ftp.icm.edu.pl/packages/linux-iproute/ip-routing/): `yymmdd`, this version isn't in our git repository.

The other maintainer YOSHIFUJI Hideaki (http://www.skbuff.net/iputils/) moved to the current scheme `syyyymmdd`, which is used in git. And main reason is not forcing everybody distros to cope with this change.

**Comment by okias** [comment]
Hello guys.

1. I don't like this `sYYYYMMDD` format either, but I think changing it - for this type of project (mostly maintanance only, no new features) is useless
2. let's drop `s`, but since `[0-9]` < `s`, we will need contact all maintainers keeping `s` inside their names:

```
Kwort 
openSuSE*
PLD Linux
```
So, everyone else already dropped the `s`.

Real impact of dropping `s` is minor, so let's do it. I'll try contact contact openSuSE guys, if anyone wants, try the other two distros.

**Comment by pevik** [comment]
@okias Yes, I can handle that.

**Comment by pevik** [comment]
FYI I plan to drop `s` in new release (#308).

**Comment by okias** [comment]
@pevik Agree, but maybe you could switch to normal versioning?  https://semver.org/

e.g. 1.0.0 or something

**Comment by pevik** [comment]
@okias I disagree with semver. @nmeyerhans is right, that semver is better for libraries or tools with some text/binary interfaces. For me I'd switch to semver on major rewrite of the project. Here `s` is just cosmetic change to avoid useless char during cosmetic release with few changes.

**Comment by okias** [comment]
I was looking at aesthetic part, but I'm fine with both solutions.

**Comment by pevik** [comment]
Implemented in release [20210202](https://github.com/iputils/iputils/releases/tag/20210202).
