### ISSUE TITLE
ping would be stuck if modify the current time to the previous time

### ISSUE THREAD

**Issue by lac-0073** [iputils/iputils#276]
It would be stucked during ping if i modify the current time to the previous time ,and will not exit normally:

Login 2 windows at the same time
1st:
[root@localhost ~]#  ping  9.82.156.184  -c 20
PING 9.82.156.184 (9.82.156.184) 56(84) bytes of data.
64 bytes from 9.82.156.184: icmp_seq=1 ttl=64 time=0.420 ms
64 bytes from 9.82.156.184: icmp_seq=2 ttl=64 time=0.480 ms
64 bytes from 9.82.156.184: icmp_seq=3 ttl=64 time=0.497 ms
64 bytes from 9.82.156.184: icmp_seq=4 ttl=64 time=0.434 ms
64 bytes from 9.82.156.184: icmp_seq=5 ttl=64 time=0.467 ms
64 bytes from 9.82.156.184: icmp_seq=6 ttl=64 time=0.413 ms
64 bytes from 9.82.156.184: icmp_seq=7 ttl=64 time=0.450 ms
64 bytes from 9.82.156.184: icmp_seq=8 ttl=64 time=0.449 ms

2st:
[root@localhost rpm]# date
Tue Jun 16 19:54:42 CST 2020
[root@localhost rpm]# date -s "2020-06-16 19:52:50"
Tue Jun 16 19:52:50 CST 2020
[root@localhost rpm]# date
Tue Jun 16 19:52:52 CST 2020

and then 1st window will be stucked  until the current time is greater than the time of the initial ping

**Comment by kerolasa** [comment]
This is not a great fix. It would be far better to use `clock_gettime(2)` CLOCK_MONOTONIC.

**Comment by lac-0073** [comment]
> This is not a great fix. It would be far better to use `clock_gettime(2)` CLOCK_MONOTONIC.

I rewrote it like you said. could you please review it again? Thank you.  #278

**Comment by lac-0073** [comment]
> > This is not a great fix. It would be far better to use `clock_gettime(2)` CLOCK_MONOTONIC.
> 
> I rewrote it like you said. could you please review it again? Thank you. #278

And I have verified this modification.

**Comment by pevik** [comment]
@ThomasHabets thanks for pointing this out. It looked to me it was fixed by https://github.com/iputils/iputils/commit/4fd276cd8211c502cb87c5db0ce15cd685177216 i.e. very similar approach you had, the only change is to use `CLOCK_MONOTONIC_RAW` (since Linux 2.6.28; Linux-specific, Similar  to  CLOCK_MONOTONIC, but provides access to a raw hardware-based time that is not subject to NTP adjustments.). I wonder whether we should use `CLOCK_MONOTONIC` to have NTP adjustments (I remember we discussed it somewhere in the past, but didn't find it now).

Also link to your patch in lore (best archive for kernel mailing lists): https://lore.kernel.org/netdev/alpine.DEB.1.10.1009051453090.13886@red.crap.retrofitta.se/

**Comment by ThomasHabets** [comment]
@pevik well, `CLOCK_MONOTONIC` and `CLOCK_MONOTONIC_RAW` both have benefits and drawbacks. Neither jumps (especially backwards), and while the latter is more likely more even, the former is likely more correct.

That is, if the actual time measured is 7ms and 7ms, do you prefer a measurement of 8ms and 7ms (`CLOCK_MONOTONIC`, deciding to adjust the speed between the two measurements), or 8ms and 8ms (measuring consistently, but less correctly, with `CLOCK_MONOTONIC_RAW`).

For benchmarking performance A/B testing I'd say `CLOCK_MONOTONIC_RAW`, but otherwise I'd likely go for `CLOCK_MONOTONIC`.

That's at least my understanding of the two.

The difference is small enough that for practical purposes it doesn't matter, though.
