### ISSUE TITLE
Limit the number of queries by default as in Windows

### ISSUE THREAD

**Issue by artenax** [iputils/iputils#453]
How do I make count 4 (-c4) by default? I would like to fix the source code and recompile. Can you help me where to fix it?
I agree with the author of this discussion
[Why does ping run forever by default in Linux?](https://unix.stackexchange.com/questions/255405/why-does-ping-run-forever-by-default-in-linux)
Infinity value by default is a bad idea. It attacks servers or forces me to specify additional options.

**Comment by pevik** [comment]
If you watch your network traffic, you'll see more traffic than just 1 sec ICMP packet. Among the traffic you see quite often `ipv6-allrouters: ICMP6, router solicitation` from radvd. There is no need from security to block ping to have -c4 by default, DDoS looks really much much heavier :). 

More danger is to flood with `-f`, but even here we lowered the minimal value for non-root from 200 ms to 2 ms (https://github.com/iputils/iputils/commit/0ccdbb9937a90f4c765fe9ab94d1441dd8680f45, https://github.com/iputils/iputils/issues/317), because there are plenty of other tools to do real DDoS than ping.

And because we strive for backward compatibility (so that people does not need to update their tooling unless a strong reason) I'm closing this.
