### ISSUE TITLE
Inconsistent ping command-line header output between IPv4 and IPv6

### ISSUE THREAD

**Issue by robert-scheck** [iputils/iputils#455]
Using iputils 20221126 from Fedora Rawhide it looks like this:

```
$ ping -4 -c 1 google.com
PING google.com (142.250.186.142) 56(84) bytes of data.
64 bytes from fra24s07-in-f14.1e100.net (142.250.186.142): icmp_seq=1 ttl=115 time=5.60 ms

--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 5.599/5.599/5.599/0.000 ms
$ 
```

```
$ ping -6 -c 1 google.com
PING google.com(fra24s07-in-x0e.1e100.net (2a00:1450:4001:82a::200e)) 56 data bytes
64 bytes from fra24s07-in-x0e.1e100.net (2a00:1450:4001:82a::200e): icmp_seq=1 ttl=114 time=5.64 ms

--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 5.643/5.643/5.643/0.000 ms
$ 
```

Why is it `google.com (142.250.186.142)` for IPv4 but `google.com(fra24s07-in-x0e.1e100.net (2a00:1450:4001:82a::200e))` for IPv6? Actually, I would expect `google.com (2a00:1450:4001:82a::200e)` for IPv6. What is the benefit of printing the reverse DNS already in the command-line header output while each row below shows it anyway? Or is this a bug?

**Comment by pevik** [comment]
IMHO that's google specific IPV6 DNS setup:
```
$ dig +nocmd +noall +answer google.com aaaa
google.com.		171	IN	AAAA	2a00:1450:4001:812::200e

$ dig +nocmd +noall +answer fra16s52-in-x0e.1e100.net aaaa
fra16s52-in-x0e.1e100.net. 3530	IN	AAAA	2a00:1450:4001:812::200e
```
`2a00:1450:4001:812::200e` is assigned to both domains thus they are both printed.

`ping` output is usual for normal records, where IP is assigned to just a single domain:
```
$ dig +nocmd +noall +answer seznam.cz a
seznam.cz.		30	IN	A	77.75.79.222
seznam.cz.		30	IN	A	77.75.77.222

$ dig +nocmd +noall +answer seznam.cz aaaa
seznam.cz.		30	IN	AAAA	2a02:598:a::79:222
seznam.cz.		30	IN	AAAA	2a02:598:2::1222

$ ping -4 -c 1 -v seznam.cz
PING  (77.75.77.222) 56(84) bytes of data.
64 bytes from www.seznam.cz (77.75.77.222): icmp_seq=1 ttl=55 time=4.54 ms

$ ping -6 -c 1 -v seznam.cz
PING seznam.cz(www.seznam.cz (2a02:598:2::1222)) 56 data bytes
64 bytes from www.seznam.cz (2a02:598:2::1222): icmp_seq=1 ttl=55 time=4.79 ms
```

**Comment by robert-scheck** [comment]
I'm not sure whether I caused a misunderstanding, but `seznam.cz(www.seznam.cz (2a02:598:2::1222))` is not what I expect, but just `seznam.cz (2a02:598:2::1222)`.

**Comment by pevik** [comment]
Now I understand you. To be honest I have no idea, why the output is not unified. I'd bet there was reason to be more verbose in IPv6. Change like this would unify IPv4 output with IPv6:

https://github.com/iputils/iputils/commit/b375b05d54f40a5db767b74fc64153da551a7b81

But there would have to be very good reason to change `ping` output, people are using it for parsing. Maybe if `ping` gains json output we can start cleanup normal output.

**Comment by robert-scheck** [comment]
But your suggestion changes the IPv4 output to match the IPv6 one, right? I would have expected to change the IPv6 output to match the IPv4 one. Coming from an IPv4 world in general, I would treat it as handy if `ping` uses the same output for IPv6 like IPv4 does. Because right now, output parsing for IPv4 (schema `argv[1] (192.0.2.0)`) doesn't apply to IPv6 (schema `argv[1] (PTR(2001:db8::1))`). Thus I would propose to change IPv6 schema to `argv[1] (2001:db8::1)`.

**Comment by pevik** [comment]
@yoshfuji please, any input?

**Comment by pevik** [comment]
I guess IPv4 version is a bit confusing, why there is another hostname. Also there are 2 spaces after `PING` in the first line of the output, instead of one space. OTOH busybox ping implementation does not print reverse DNS lookup, thus I'm not sure.

**Comment by pevik** [comment]
@nmeyerhans any input, please?

**Comment by nmeyerhans** [comment]
I don't see a lot of value in the reverse DNS lookup. It's not needed in order to fulfill ping's core functionality, and can be obtained using other dedicated tools if really needed.

It's even weirder in cases where the remote host doesn't have a reverse DNS entry, with the resolved target IP address listed twice in nested parenthesis:

```plain
$ ping -6 -c1 s3.dualstack.us-west-2.amazonaws.com
PING s3.dualstack.us-west-2.amazonaws.com(2600:1fa0:40df:ac41:345c:b4c8:: (2600:1fa0:40df:ac41:345c:b4c8::)) 56 data bytes
64 bytes from 2600:1fa0:40df:ac41:345c:b4c8:: (2600:1fa0:40df:ac41:345c:b4c8::): icmp_seq=1 ttl=221 time=18.6 ms

--- s3.dualstack.us-west-2.amazonaws.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 18.559/18.559/18.559/0.000 ms
```

I'd be in favor of adding the missing space character after the target hostname on the `PING` line and avoiding the reverse DNS lookup.

So the output would be something like the following if "example.com" is the given target and resolves to 2001:db8:1234:1234::1 in DNS:

`PING example.com (2001:db8:1234:1234::1) 56 data bytes`

I'd also like to see the IPv4 version use a similar output format for that line. I share the earlier concerns about changing ping's output format, but I don't think that needs stop us from making these improvements.

**Comment by pevik** [comment]
> I'd be in favor of adding the missing space character after the target hostname on the PING line and avoiding the reverse DNS lookup.

+1 for adding space. Would you have time to send PR?

We have `-n` to avoid reverse DNS lookup. I wonder if we keep it as a default (i.e. `-n` or *nothing* would *not* do reverse DNS lookup) and add non-default `-R` (not many options left) which would *do* reverse DNS lookup.

We need to keep `-n` for backwards compatibility). And people may want to have reverse DNS lookup, that's why I'd consider to keep it as non-default. Or we can decide to remove it and re-add it as `-R` if people complain.

Again, feel free to send it as PR, but please if not 2 separate PR's then as 2 separate commits (unifying space is IMHO separated thing, which should stay).
